### ISSUE TITLE
Expected to find an array at path ... but found 'map[interface {}]interface {}'

### ISSUE THREAD

**Issue by FulcrumTeam** [cppforlife/go-patch#21]
Hello, getting an error (the title) when trying to replace (add) what I think is an array element.

Here is the manifest block I'm trying to match on:
```
       - job_name: bosh
          scrape_interval: 2m
          scrape_timeout: 1m
          static_configs:
          **- targets:
            - localhost:9190**
```

my replace statement:
```
- type: replace
path: /.../job_name=bosh/static_configs/targets/-
value: "192.168.164.26:9190"
```
How can I add another value to targets?
