### ISSUE TITLE
Appending many items to an array

### ISSUE THREAD

**Issue by drich10** [cppforlife/go-patch#4]
It would be lovely if I could append multiple items in a single operation. It can become a bit unwieldily writing it many times.

```
- type: replace
  path: /releases/-
  value:
    name: extra-release-0
    version: 0
    url: file://extra-release-0

- type: replace
  path: /releases/-
  value:
    name: extra-release-1
    version: 1
    url: file://extra-release-1

- type: replace
  path: /releases/-
  value:
    name: extra-release-2
    version: 2
    url: file://extra-release-2
```

--->
```
?
```
Wish I had a good suggestion for what could be done here 😋

**Comment by jtarchie** [comment]
A proposal:

```yaml
- type: append
  path: /releases/
  values:
    -  name: extra-release-0
       version: 0
       url: file://extra-release-0
    -  name: extra-release-1
       version: 1
       url: file://extra-release-1
    -  name: extra-release-2
       version: 2
       url: file://extra-release-2
```
