### ISSUE TITLE
Ability to match multiple elements in an array

### ISSUE THREAD

**Issue by aeijdenberg** [cppforlife/go-patch#8]
We would find it useful to be able to apply a `replace` pattern to all elements in an array.

For example:

```yaml
- type: replace
  path: /instance_groups/*/vm_extensions?/-
  value: foo
```

This would be not be allowed as the last element - only as an intermediate one, and is only valid for the `replace` and `remove` operations.
